# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crsh < Formula
  desc "CRSH — Monitor and control AI coding sessions from any device"
  homepage "https://crsh.ai"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.1/crsh_0.0.1_darwin_amd64.tar.gz"
      sha256 "f3d7f0616c3bab4d45e44b2926cb20899e34568f089ceb2769d292fc618caf5a"

      define_method(:install) do
        bin.install "crsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.1/crsh_0.0.1_darwin_arm64.tar.gz"
      sha256 "0acbae2bf56f1fd0bf1f46c72065f31acf57bf7114c2e821f2f332a0ad504125"

      define_method(:install) do
        bin.install "crsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.1/crsh_0.0.1_linux_amd64.tar.gz"
      sha256 "8700b345767ae20005ed5c3704b30dff3aedfca637c688486e9e5fdd976c3d18"
      define_method(:install) do
        bin.install "crsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.1/crsh_0.0.1_linux_arm64.tar.gz"
      sha256 "4f72b894c7e8d782cfcd926c9b1ad80c2c7a3f379cf7f51276f51fadaac5040b"
      define_method(:install) do
        bin.install "crsh"
      end
    end
  end

  test do
    system "#{bin}/crsh", "version"
  end
end
