# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crsh < Formula
  desc "CRSH — Monitor and control AI coding sessions from any device"
  homepage "https://crsh.ai"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.2/crsh_0.0.2_darwin_amd64.tar.gz"
      sha256 "dd8760b89fb441c119a69375b3e7daa82534908866d4601977e7b505630fe43c"

      define_method(:install) do
        bin.install "crsh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.2/crsh_0.0.2_darwin_arm64.tar.gz"
      sha256 "4e874047dd1dd401160ae611e1cfdaa4336307399a127a1495f8083978fa670e"

      define_method(:install) do
        bin.install "crsh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.2/crsh_0.0.2_linux_amd64.tar.gz"
      sha256 "9ba815e6f523f4ef709b605716a1077e83d09c4970c3a267daa316588ce0ef59"
      define_method(:install) do
        bin.install "crsh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/crshai/crsh-releases/releases/download/v0.0.2/crsh_0.0.2_linux_arm64.tar.gz"
      sha256 "ad9aa6d56ef57766331a5658cc0b59221fbf357c64939180053ffb29979d0a0d"
      define_method(:install) do
        bin.install "crsh"
      end
    end
  end

  test do
    system "#{bin}/crsh", "version"
  end
end
